// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "CloudSweep Support",
            "url": "https://github.com/ermt0504/cloud-sweep",
            "email": "support@cloudsweep.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cleanup": {
            "post": {
                "description": "Queue a cleanup operation for specified resources",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cleanup"
                ],
                "summary": "Execute cleanup",
                "parameters": [
                    {
                        "description": "Cleanup request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ExecuteCleanupRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/handler.ExecuteCleanupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cleanup/preview": {
            "post": {
                "description": "Preview what resources would be affected by a cleanup operation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cleanup"
                ],
                "summary": "Preview cleanup",
                "parameters": [
                    {
                        "description": "Cleanup preview request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ExecuteCleanupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.CleanupPreviewDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/carbon": {
            "get": {
                "description": "Get carbon footprint breakdown by provider and region",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Carbon footprint breakdown",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.CarbonResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/savings": {
            "get": {
                "description": "Get potential savings breakdown by provider and resource type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Savings breakdown",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SavingsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/summary": {
            "get": {
                "description": "Get dashboard summary statistics including total resources, unused resources, costs and carbon footprint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Dashboard summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/handler.SummaryStats"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Basic health check endpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.HealthResponse"
                        }
                    }
                }
            }
        },
        "/policies": {
            "get": {
                "description": "Get a paginated list of cleanup policies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policies"
                ],
                "summary": "List policies",
                "parameters": [
                    {
                        "enum": [
                            "aws",
                            "azure",
                            "gcp"
                        ],
                        "type": "string",
                        "description": "Filter by cloud provider",
                        "name": "provider",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by enabled status",
                        "name": "is_enabled",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Number of items to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.PolicyDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new cleanup policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policies"
                ],
                "summary": "Create policy",
                "parameters": [
                    {
                        "description": "Policy request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreatePolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/handler.PolicyDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/policies/{id}": {
            "get": {
                "description": "Get a single policy by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policies"
                ],
                "summary": "Get policy by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Policy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/handler.PolicyDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policies"
                ],
                "summary": "Update policy",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Policy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Policy update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreatePolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/handler.PolicyDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policies"
                ],
                "summary": "Delete policy",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Policy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/policies/{id}/disable": {
            "post": {
                "description": "Disable a policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policies"
                ],
                "summary": "Disable policy",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Policy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/policies/{id}/enable": {
            "post": {
                "description": "Enable a policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policies"
                ],
                "summary": "Enable policy",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Policy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Readiness check with dependency verification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ReadyResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/resources": {
            "get": {
                "description": "Get a paginated list of cloud resources with optional filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Resources"
                ],
                "summary": "List resources",
                "parameters": [
                    {
                        "enum": [
                            "aws",
                            "azure",
                            "gcp"
                        ],
                        "type": "string",
                        "description": "Filter by cloud provider",
                        "name": "provider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by resource type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "active",
                            "unused",
                            "deleted",
                            "excluded"
                        ],
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by region",
                        "name": "region",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Number of items to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.ResourceDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/resources/{id}": {
            "get": {
                "description": "Get a single cloud resource by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Resources"
                ],
                "summary": "Get resource by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Resource ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/handler.ResourceDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Mark a resource as deleted",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Resources"
                ],
                "summary": "Delete resource",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Resource ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/scans": {
            "get": {
                "description": "Get a paginated list of scans with optional filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scans"
                ],
                "summary": "List scans",
                "parameters": [
                    {
                        "enum": [
                            "aws",
                            "azure",
                            "gcp"
                        ],
                        "type": "string",
                        "description": "Filter by cloud provider",
                        "name": "provider",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "pending",
                            "running",
                            "completed",
                            "failed",
                            "cancelled"
                        ],
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Number of items to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.ScanDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new cloud resource scan and queue it for processing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scans"
                ],
                "summary": "Create a new scan",
                "parameters": [
                    {
                        "description": "Scan request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateScanRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.CreateScanResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/scans/{id}": {
            "get": {
                "description": "Get a single scan by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Scans"
                ],
                "summary": "Get scan by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Scan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/handler.ScanDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.CarbonResponse": {
            "type": "object",
            "properties": {
                "by_provider": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ProviderCarbon"
                    }
                },
                "by_region": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.RegionCarbon"
                    }
                }
            }
        },
        "handler.CleanupPreviewDTO": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "example": "delete"
                },
                "count": {
                    "type": "integer",
                    "example": 5
                },
                "estimated_carbon_savings": {
                    "type": "number",
                    "example": 35.5
                },
                "estimated_monthly_savings": {
                    "type": "number",
                    "example": 250
                },
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ResourceDTO"
                    }
                }
            }
        },
        "handler.CreatePolicyRequest": {
            "type": "object",
            "required": [
                "actions",
                "name",
                "organization_id",
                "provider"
            ],
            "properties": {
                "actions": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "notify",
                        "delete"
                    ]
                },
                "conditions": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "description": {
                    "type": "string",
                    "example": "Automatically delete EBS volumes unused for 30 days"
                },
                "name": {
                    "type": "string",
                    "example": "Delete unused EBS volumes"
                },
                "organization_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "provider": {
                    "type": "string",
                    "enum": [
                        "aws",
                        "azure",
                        "gcp"
                    ],
                    "example": "aws"
                },
                "resource_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "ebs_volume",
                        "ebs_snapshot"
                    ]
                },
                "schedule": {
                    "type": "string",
                    "example": "0 0 * * *"
                }
            }
        },
        "handler.CreateScanRequest": {
            "type": "object",
            "required": [
                "organization_id",
                "provider",
                "regions"
            ],
            "properties": {
                "organization_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "provider": {
                    "type": "string",
                    "enum": [
                        "aws",
                        "azure",
                        "gcp"
                    ],
                    "example": "aws"
                },
                "regions": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "us-east-1",
                        "eu-west-1"
                    ]
                },
                "resource_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "ec2_instance",
                        "ebs_volume"
                    ]
                }
            }
        },
        "handler.CreateScanResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.ScanDTO"
                },
                "message": {
                    "type": "string",
                    "example": "scan created and queued for processing"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid request"
                }
            }
        },
        "handler.ExecuteCleanupRequest": {
            "type": "object",
            "required": [
                "action",
                "organization_id",
                "resource_ids"
            ],
            "properties": {
                "action": {
                    "type": "string",
                    "enum": [
                        "delete",
                        "stop",
                        "tag",
                        "notify"
                    ],
                    "example": "delete"
                },
                "dry_run": {
                    "type": "boolean",
                    "example": false
                },
                "organization_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "resource_ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "550e8400-e29b-41d4-a716-446655440001",
                        "550e8400-e29b-41d4-a716-446655440002"
                    ]
                }
            }
        },
        "handler.ExecuteCleanupResponse": {
            "type": "object",
            "properties": {
                "dry_run": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "cleanup task queued"
                },
                "task_id": {
                    "type": "string",
                    "example": "task_12345"
                }
            }
        },
        "handler.HealthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "example": "cloudsweep-api"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "handler.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "operation successful"
                }
            }
        },
        "handler.PaginatedResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "limit": {
                    "type": "integer",
                    "example": 50
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "total": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "handler.PolicyDTO": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "notify",
                            "tag",
                            "stop",
                            "delete"
                        ]
                    },
                    "example": [
                        "notify",
                        "delete"
                    ]
                },
                "conditions": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "example": "Automatically delete EBS volumes unused for 30 days"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "is_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Delete unused EBS volumes"
                },
                "organization_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "provider": {
                    "type": "string",
                    "enum": [
                        "aws",
                        "azure",
                        "gcp"
                    ],
                    "example": "aws"
                },
                "resource_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "ebs_volume"
                    ]
                },
                "schedule": {
                    "type": "string",
                    "example": "0 0 * * *"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "handler.ProviderCarbon": {
            "type": "object",
            "properties": {
                "carbon_kg": {
                    "type": "number",
                    "example": 450.25
                },
                "potential_savings_kg": {
                    "type": "number",
                    "example": 75.5
                },
                "provider": {
                    "type": "string",
                    "example": "aws"
                }
            }
        },
        "handler.ProviderSavings": {
            "type": "object",
            "properties": {
                "monthly_cost": {
                    "type": "number",
                    "example": 1500
                },
                "potential_savings": {
                    "type": "number",
                    "example": 250
                },
                "provider": {
                    "type": "string",
                    "example": "aws"
                },
                "unused_count": {
                    "type": "integer",
                    "example": 25
                }
            }
        },
        "handler.ReadyResponse": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "ready"
                }
            }
        },
        "handler.RegionCarbon": {
            "type": "object",
            "properties": {
                "carbon_kg": {
                    "type": "number",
                    "example": 250
                },
                "region": {
                    "type": "string",
                    "example": "us-east-1"
                }
            }
        },
        "handler.ResourceDTO": {
            "type": "object",
            "properties": {
                "carbon_footprint_kg": {
                    "type": "number",
                    "example": 12.5
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "last_seen_at": {
                    "type": "string"
                },
                "monthly_cost": {
                    "type": "number",
                    "example": 45.5
                },
                "name": {
                    "type": "string",
                    "example": "my-instance"
                },
                "organization_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "provider": {
                    "type": "string",
                    "enum": [
                        "aws",
                        "azure",
                        "gcp"
                    ],
                    "example": "aws"
                },
                "region": {
                    "type": "string",
                    "example": "us-east-1"
                },
                "resource_id": {
                    "type": "string",
                    "example": "i-1234567890abcdef0"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "active",
                        "unused",
                        "deleted",
                        "excluded"
                    ],
                    "example": "unused"
                },
                "tags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string",
                    "example": "ec2_instance"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "handler.SavingsResponse": {
            "type": "object",
            "properties": {
                "by_provider": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ProviderSavings"
                    }
                },
                "by_resource_type": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.TypeSavings"
                    }
                }
            }
        },
        "handler.ScanDTO": {
            "type": "object",
            "properties": {
                "carbon_savings_kg": {
                    "type": "number",
                    "example": 45.5
                },
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "estimated_savings": {
                    "type": "number",
                    "example": 1250
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "organization_id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "provider": {
                    "type": "string",
                    "enum": [
                        "aws",
                        "azure",
                        "gcp"
                    ],
                    "example": "aws"
                },
                "regions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "us-east-1",
                        "eu-west-1"
                    ]
                },
                "resource_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "ec2_instance",
                        "ebs_volume"
                    ]
                },
                "resources_found": {
                    "type": "integer",
                    "example": 150
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "pending",
                        "running",
                        "completed",
                        "failed",
                        "cancelled"
                    ],
                    "example": "completed"
                },
                "unused_found": {
                    "type": "integer",
                    "example": 23
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "handler.SummaryStats": {
            "type": "object",
            "properties": {
                "potential_carbon_savings_kg": {
                    "type": "number",
                    "example": 180.25
                },
                "potential_monthly_savings": {
                    "type": "number",
                    "example": 2500
                },
                "total_carbon_kg": {
                    "type": "number",
                    "example": 1200.5
                },
                "total_monthly_cost": {
                    "type": "number",
                    "example": 15000
                },
                "total_resources": {
                    "type": "integer",
                    "example": 500
                },
                "unused_resources": {
                    "type": "integer",
                    "example": 75
                }
            }
        },
        "handler.TypeSavings": {
            "type": "object",
            "properties": {
                "monthly_cost": {
                    "type": "number",
                    "example": 800
                },
                "resource_type": {
                    "type": "string",
                    "example": "ec2_instance"
                },
                "unused_count": {
                    "type": "integer",
                    "example": 10
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer token authentication",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "CloudSweep API",
	Description:      "API FinOps/GreenOps pour automatiser le nettoyage des ressources cloud inutilisees",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
